[package]
name = "permanent_tester"
version = "0.1.0"
edition = "2021"

[dependencies]
permanent_common = { path = "../permanent_common" }
clap = { version="4.3.22", features=["derive"] }
serde = "1.0.183"
serde_yaml = "0.9.25"
serde_json = "1.0.105"
blake3 = "1.4.1"
itertools = "0.11.0"
