[package]
name = "permanent_common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bincode = "1.3.3"
enumset = "1.1.2"
serde = { version = "1.0.183", features = ["derive"] }
snap = "1.0.5"
